#!/bin/bash

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

rm -rf /root/log-limit.txt
touch /root/log-limit.txt
clear
Green_font_prefix="\033[32m" && Red_font_prefix="\033[31m" && Green_background_prefix="\033[42;37m" && Red_background_prefix="\033[41;37m" && Font_color_suffix="\033[0m"
Info="${Green_font_prefix}ON${Font_color_suffix}"
Error="${Red_font_prefix}OFF${Font_color_suffix}"
cek=$(grep -c -E "^# Autokill" /etc/cron.d/tendang)
if [[ "$cek" = "1" ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear
echo -e ""
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "            Status Autokill $sts           "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "       1. AutoKill After 1 Minutes"
echo -e "       2. AutoKill After 2 Minutes"
echo -e "       3. AutoKill After 3 Minutes"
echo -e "       4. Turn Off AutoKill/MultiLogin"
echo -e "       5. Exit"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e ""
read -p " MENU : " AutoKill
echo -e ""
case $AutoKill in
                1)
                echo -e ""
                read -p "  Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/1 * * * *  root /usr/local/sbin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                echo -e ""
                echo -e "      Allowed MultiLogin : $max"
                echo -e "      AutoKill Every     : 1 Minutes"      
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
                autokill                                
                ;;
                2)
                echo -e ""
                read -p "  Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/2 * * * *  root /usr/local/sbin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                echo -e ""
                echo -e "        Allowed MultiLogin : $max"
                echo -e "        AutoKill Every     : 2 Minutes"
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
                autokill
                ;;
                3)
                echo -e ""
                read -p "  Multilogin Maximum Number Of Allowed: " max
                sleep 1
                clear
                echo > /etc/cron.d/tendang
                echo "# Autokill" >>/etc/cron.d/tendang
                echo "*/3 * * * *  root /usr/local/sbin/tendang $max" >>/etc/cron.d/tendang
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                echo -e ""
                echo -e "        Allowed MultiLogin : $max"
                echo -e "        AutoKill Every     : 3 Minutes"
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
                autokill
                ;;
                4)
                clear
                echo > /etc/cron.d/tendang
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                echo -e ""
                echo -e "        AutoKill MultiLogin Turned Off  "
                echo -e ""
                echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━━━━◈ ${NC}"
                read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
                autokill
                ;;
                0 | 00 | x | X | 0x | 0X)
                clear
                menu
                ;;
        esac
        