#!/bin/bash

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'

# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/sshmax07/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc

clear
function con() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "        CEK KUOTA AKUN VLESS      "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"

data=( `grep '^#&' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq` )

for akun in "${data[@]}"; do
    if [[ -z "$akun" ]]; then
        akun="tidakada"
    fi
    
    byte=$(cat /etc/vless/${akun}) 2>/dev/null
    if [[ -z "$byte" ]]; then
        byte=0
    fi
    
    usage_quota=$(con $byte)
    
    lim=$(cat /etc/limit/vless/${akun}) 2>/dev/null
    if [[ -z "$lim" ]]; then
        lim=0
    fi
    limit_quota=$(con $lim)

    # Mendapatkan waktu login
    last_login=$(grep -w "$akun" /var/log/xray/access.log | tail -n 1 | awk '{print $2}') 2>/dev/null
    if [[ -z "$last_login" ]]; then
        last_login="Tidak ada"
    fi
    
    ip_count=$(grep -w "$akun" /var/log/xray/access.log | awk '{print $3}' | sed 's/tcp://g' | cut -d ':' -f 1 | sort | uniq | wc -l)

    echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
    printf "    %-13s %-7s\n" "UserName : ${akun}"
    printf "    %-13s %-7s\n" "Total Bandwidth : ${limit_quota}" 
    printf "    %-13s %-7s\n" "Last Login : ${last_login}"
    printf "    %-13s %-7s\n" "Login IP : ${ip_count}"
    echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
done

echo ""
read -p "ENTER UNTUK KEMBALI KE MENU"
m-vless