#!/bin/bash

# Color
RED='\033[0;31m'
NC='\033[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

clear
echo " "
echo -e "\033[92m◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ \033[0m"
echo -e "            CEK AKUN MULTY LOGIN           "
echo -e "\033[92m◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ \033[0m"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo " ";
if [ -e "/root/log-limit.txt" ]; then
echo " User Who Violate The Maximum Limit";
echo " Time - Username - Number of Multilogin"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
cat /root/log-limit.txt
else
echo " No user has committed a violation"
echo " "
echo " or"
echo " "
echo " The user-limit script not been executed."
fi
echo " ";
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo " "
read -n 1 -s -r -p "ENTER UNTUK KEMBALI KE MENU"
menu