#!/bin/bash

# pewarna hidup
red='\e[1;31m'
Lgreen='\033[92m'
PURPLE='\033[35m'
green="\033[1;97m"
blue="\033[1;96m"
NC='\e[0m'
clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "               KUNCI AKUN SSH               "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo "USERNAME          EXP DATE          STATUS"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp   "
else
printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp   "
fi
fi
done < /etc/passwd
echo -e "\033[92m◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ \033[0m"
echo -e "\033[35m◈━━━━◈◈━━━━◈ \033[0m"
read -p " Pengguna : " username
egrep "^$username" /etc/passwd >/dev/null
passwd -l $username
clear
  echo " "
  echo " "
  echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
  echo -e "Username ${blue}$username${NC} Sukses Di ${red}LOCKED !${NC}."
  echo -e "Akses Login username ${blue}$username${NC} Telah Di locked."
  echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
  systemctl restart ws
  echo ""
read -n 1 -s -r -p " ENTUK UNTUKBKEMBALI KE MENU"
menu
