#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\033[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/sshmax07/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    exit 0
  fi
}
checking_sc
clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "              MENU VMESS              "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "$NC [${Lgreen}01${NC}]. BUAT AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}02${NC}]. BUAT TRIAL AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}03${NC}]. HAPUS AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}04${NC}]. PERBARUI AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}05${NC}]. PERBARUI IP VMESS${NC}"
echo -e "$NC [${Lgreen}06${NC}]. PERBARUI KUOTA VMESS${NC}"
echo -e "$NC [${Lgreen}07${NC}]. CEK LOGIN AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}08${NC}]. CEK KUOTA AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}09${NC}]. DAFTAR AKUN VMESS${NC}"
echo -e "$NC [${Lgreen}00${NC}]. ENTER UNTUK KEMBALI KE MENU${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "\033[92m◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ \033[0m"
echo -e "            🇯‌🇳‌🇸‌🇹‌🇴‌🇷‌🇪‌        "
echo -e "\033[92m◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ \033[0m"
echo -e ""
read -p "MENU : " menu
case $menu in
1)   clear ;
    addws
    ;;
2) clear ;
    trialws
    ;;
3) clear ;
    delws
    ;;
4) clear ;
    renewws
    ;;
5) clear ;
renew-ip-vmess
    ;;
6) clear ;
renew-quota-vmess
    ;;
7) clear ;
    cekws
    ;;
8) clear ;
    cekbwws
    ;;
9) clear ;
    userws
    ;;
*) clear ;
    menu
    ;;
esac