#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
PURPLE='\033[35m'
Lgreen='\033[92m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/sshmax07/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc
clear

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
NS=$(cat /etc/xray/dns)
PUB=$(cat /etc/slowdns/server.pub)
clear
IP=$(curl -sS ipv4.icanhazip.com)
Login=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         BUAT TRIAL AKUN SSH    "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━◈◈━━━━◈ ${NC}"
read -p " Set Menit : " pup
hari="1"
Pass=1
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
<code>TRIAL SSH OPENVPN PREMIUM</code>
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
<code>IP Address :</code> <code>$IP</code>
<code>Hostname   :</code> <code>$domain</code>
<code>Username   :</code> <code>$Login</code>
<code>Password   :</code> <code>$Pass</code>
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
<code>
OpenSSH      : 22
Dropbear     : 443, 109, 143
SSL/TLS      : 400-900
SSH WS TLS   : 443
SSH WS NTLS  : 80, 8080, 8081-9999
OVPN WS TLS  : 443
OVPN WS NTLS : 80, 8080, 8880
PORT SSH UDP : 7100,7200,7300</code>
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
Ovpn Download : https://$domain:81/
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
Save Link Account: https://$domain:81/ssh-$Login.txt
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>
Berakhir Pada  : $pup Menit
<code>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</code>"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
mkdir -p /etc/ssh

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${Login}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${Login}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${Login} " >>/etc/ssh/.ssh.db
echo ""
cat > /var/www/html/ssh-$Login.txt <<-END
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Format SSH OVPN Account
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Username         : $Login
Password         : $Pass
Berakhir Pada    : $pup Menit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Payload WSS : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OVPN Download : https://$domain:81/
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

END
echo userdel -f "$Login" | at now + $pup minutes
echo "tunnel ssh ${Login}" | at now +$pup minutes &> /dev/null
clear
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» INFORMASI AKUN « " | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Domain  : $domain" | tee -a /etc/user-create/user.log
echo -e "» Pengguna  : $Login" | tee -a /etc/user-create/user.log
echo -e "» Sandi  : $Pass" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Slowdns  : ${NS}" | tee -a /etc/user-create/user.log
echo -e "» Pub Key  : ${PUB}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Port OpenSSH  : 443, 80, 22" | tee -a /etc/user-create/user.log
echo -e "» Port DNS  : 443, 53 ,22 " | tee -a /etc/user-create/user.log
echo -e "» Port SSH UDP  : 1-65535" | tee -a /etc/user-create/user.log
echo -e "» Port Dropbear  : 443, 109" | tee -a /etc/user-create/user.log
echo -e "» Port SSH WS  : 80, 8080, 8880, 2082" | tee -a /etc/user-create/user.log
echo -e "» BadVPN  : 7100, 7300, 7300" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» SSH-80  : $domain:80@$Login:$Pass" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» SSH-443  : $domain:443@$Login:$Pass" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» SSH-UDP : $domain:1-65535@$Login:$Pass" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» WEBSOCKED" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e " GET / HTTP/1.1[crlf]host: $domain[crlf]Upgrade: Websocket[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» ENHANCED" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "GET / HTTP/1.1[crlf]Host: bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 200[crlf][crlf]" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
echo -e "» Batas Ip  : $iplimit Device" | tee -a /etc/user-create/user.log
echo -e "» Batas Kuota  : $Quota GB" | tee -a /etc/user-create/user.log
echo -e "» Aktif Selama  : $pup menit" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
echo ""  | tee -a /etc/user-create/user.log
read -n 1 -s -r -p "ENTER UNTUK KEMBALI KE MENU"
menu