#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
PURPLE='\033[35m'
Lgreen='\033[92m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/sshmax07/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc
clear
domain=$(cat /etc/xray/domain)
masaaktif=1
Quota=1
iplimit=10
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         BUAT TRIAL AKUN TROJAN    "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━◈◈━━━━◈ ${NC}"
read -p " Set Menit : " pup
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink3="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END
━━━━━━━━━━━━━━━━━━━━━
   Format For Clash
━━━━━━━━━━━━━━━━━━━━━
# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}
        
# Format Vless WS Non TLS

- name: Trojan-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: trojan
  password: ${uuid}
  skip-cert-verify: true
  sni:null
  network: ws
  ws-opts:
    path: /trojan-ws
    headers:
      Host: ${domain}
  udp: true

# Format Trojan gRPC

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

━━━━━━━━━━━━━━━━━━━━━
Link Akun Trojan 
━━━━━━━━━━━━━━━━━━━━━
Link WS          : 
${trojanlink}
━━━━━━━━━━━━━━━━━━━━━
Link GRPC        : 
${trojanlink1}
━━━━━━━━━━━━━━━━━━━━━

END

service cron restart
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink3="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
clear
echo -e ""
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» INFORMASI AKUN « " | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Domain  : ${domain}" | tee -a /etc/user-create/user.log
echo -e "» Pengguna  : ${user}"  | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Port TLS : 443"  | tee -a /etc/user-create/user.log
echo -e "» Port NTLS  : 80, 8080, 8880, 2082" | tee -a /etc/user-create/user.log
echo -e "» Key  : ${uuid}"  | tee -a /etc/user-create/user.log
#echo -e "» Xray Dns. : ${NS}" | tee -a /etc/user-create/user.log
#echo -e "» Pubkey. : ${PUB}" | tee -a /etc/user-create/user.log
echo -e "» Path  : /trojan-ws/multi-path" | tee -a /etc/user-create/user.log
echo -e "» ServiceName  : trojan-grpc"  | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» TROJAN TLS" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${trojanlink}"  | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» TROJAN NTLS" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${trojanlink3}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» TROJAN GRPC" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${trojanlink1}"  | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
echo -e "» Batas Ip  : ${iplimit} Device" | tee -a /etc/user-create/user.log
echo -e "» Batas Kuota  : ${Quota} GB" | tee -a /etc/user-create/user.log
echo -e "» Aktif Selama  : $pup menit" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
echo "tunnel trojan ${user}" | at now +$pup minutes &> /dev/null
echo "" 
read -n 1 -s -r -p "ENTER UNTUK KEMBALI KE MENU"
menu