#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
PURPLE='\033[35m'
Lgreen='\033[92m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "           BUKA KUNCI AKUN SSH              "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo "      PENGGUNA          DATA EXP          "
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp   "
else
printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp   "
fi
fi
done < /etc/passwd
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━◈◈━━━━◈ ${NC}"
read -p " Pengguna : " username
egrep "^$username" /etc/passwd >/dev/null
passwd -u $username
clear
  echo " "
  echo " "
  echo " "
  echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
  echo -e "Username ${blue}$username${NC} Sukses Di ${green}UNLOCKED${NC}."
  echo -e "Akses Dengan Username ${blue}$username${NC} Telah Berhasil Di Unlock"
  echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
  echo ""
read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
menu