#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")
NC="\e[0m"
Lgreen='\033[92m'
PURPLE='\033[35m'

# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/sshmax07/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         DAFTAR AKUN TROJAN          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
clients=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u)
NUMBER_OF_CLIENTS=$(echo "$clients" | wc -l)

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         DAFTAR AKUN TROJAN          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "$clients"|    nl -s ') '
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
read -rp "Pilih Klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

if [[ -z "$CLIENT_NUMBER" ]]; then
    m-trojan
    exit 0
fi

if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Trojan..."
    m-trojan
    exit 1
fi

selected_client=$(echo "$clients" | sed -n "${CLIENT_NUMBER}p")
export user=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
export harini=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
export exp=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)
user=$(echo "$selected_client" | cut -d ' ' -f 1)
exp=$(echo "$selected_client" | cut -d ' ' -f 2)
domain=$(cat /etc/xray/domain)
none="$(cat ~/log-install.txt | grep -w "Vmess WS none TLS" | cut -d: -f2|sed 's/ //g')"
acs=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/trojan-ws",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/trojan-ws",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "trojan-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

 "${uuid}@${domain}:443" dan "${uuid}@${domain}:80"
encoded_tls=$(echo -n "${uuid}@${domain}:443" | base64)
encoded_ntls=$(echo -n "${uuid}@${domain}:80" | base64)
encoded_grpc=$(echo -n "${uuid}@${domain}:443" | base64)
systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1
clear
clear
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» INFORMASI AKUN « "
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» Domain  : ${domain}"
echo -e "» Pengguna  : ${user}" 
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» Port TLS  : 443"
echo -e "» Port NTLS  : 80, 8080, 8880, 2082"
echo -e "» id  : ${uuid}"
#echo -e "» Xray Dns  : ${NS}"
#echo -e "» Pubkey  : ${PUB}"
echo -e "» alterId  : 0"
echo -e "» Security  : auto"
echo -e "» Network  : ws"
echo -e "» Path  : /trojan-ws/multi-path"
#echo -e "» Patch Wildcard  : betaa.zoom.us.${domain}" | tee -a /etc/user-create/user.log
echo -e "» ServiceName  : trojan-grpc"
#echo -e "» Host XrayDNS : ${NS}" | tee -a /etc/user-create/user.log
#echo -e "» Pub Key  : ${PUB}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» TROJAN TLS"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${trojanlink}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» TROJAN NON TLS"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${trojanlink2}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» TROJAN GRPC"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${trojanlink1}"
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
#echo -e "» Batas Ip  : ${iplim Device}"
#echo -e "» Batas Kuota  : ${Quota GB} GB"
#echo -e "» Aktif Selama  : ${masaaktif Hari}"
#echo -e "» Tanggal Dibuat  : ${tnggl}"
echo -e "» Tanggal Exp  : ${exp}"
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"
echo -e ""
read -n 1 -s -r -p "ENTER UNTUK KEMBALI KE MENU"
m-trojan
